name: Restore the dotnet-file tool
author: David G. Moore, Jr., <david@dgmjr.io>
description: Restores the dotnet-file tool
branding:
   icon: file-plus
   color: green

runs:
  using: composite
  steps: 
     - id: Ensure-dotnet-file-is-installed
       run: ./scrips/ensure-dotnet-file-is-installed.sh
       shell: bash
