name: Restore the dotnet-file tool
author: David G. Moore, Jr., <david@dgmjr.io>
description: Restores the dotnet-file tool
branding:
   icon: file-plus
   color: green

runs:
  using: composite
  steps: 
    run: |
      set dotnetFileExists = $(dotnet tool list --global|grep dotnet-file);
      echo "Dotnet-file exists: $dotnetFileExists";
      if [ -Z $dotnetFileExists ]
          then 
              dotnet tool update --global dotnet-file 
          else
              dotnet tool install --global dotnet-file 
      fi
    shell: bash
