name: Restore dotnet-file
author: David G. Moore, Jr., <david@dgmjr.io>
description: Restores the dotnet-file tool
branding:
  icon: file-plus
  color: green

runs:
  using: composite
  steps: 
    - uses: actions/checkout@v3
    - id: Restore-dotnet-file
      shell: bash
      run: dotnet tool install -g dotnet-file 
