
name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  ci-build:
    runs-on: ubuntu-latest
  
    steps:
      # Runs a single command using the runners shell
      - name: Run dotnet-file-restore
        uses: dgmjr-actions/restore-dotnet-file@main
      
      - name: Ensure dotnet-file is installed
        shell: bash
        run: if [ -z $(which dotnet-file | grep dotnet-file) ]; then exit 1; fi;
